"""new field in user modedel

Revision ID: 1524b9f31b43
Revises: 01de5e1b59f8
Create Date: 2020-04-16 00:40:30.335209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1524b9f31b43'
down_revision = '01de5e1b59f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seeen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seeen')
    # ### end Alembic commands ###
