"""cost added in post

Revision ID: a571c38b8c8c
Revises: 1524b9f31b43
Create Date: 2020-04-16 01:39:39.562863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a571c38b8c8c'
down_revision = '1524b9f31b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'cost')
    # ### end Alembic commands ###
